modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="etbmod"
version="${file.jarVersion}"
displayName="Elite Trainer Box Mod"
credits="Pokemon TCG Community"
authors="ETB Mod Team"
description='''Brings Pokemon TCG Elite Trainer Boxes to Minecraft!

Features in v5.1:
- 20 unique ETB designs from real Pokemon TCG sets
- Custom orthographic textures extracted from real ETB images
- Directional placement - rotate your ETBs
- Scissors tool to open ETBs and get booster packs
- Multiple booster pack items with high-quality textures
- Gamer Table - Interactive block with GUI
- Open booster packs on the Gamer Table!
- Realistic card pack opening experience
- 10 cards per pack with accurate rarity distribution
- Navigate through cards with arrow keys
- Fully self-contained - all card data included in mod!
- Multiple complete Pokemon TCG sets with thousands of cards
- Cards load from mod resources (works on any server)
- NEW in v5.1: 7 additional ETB designs
- NEW in v5.1: Improved texture processing with transparent backgrounds
- NEW in v5.1: Orthographic front and side views for realistic appearance
'''

[[dependencies.etbmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.etbmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
