modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="etbmod"
version="${file.jarVersion}"
displayName="Elite Trainer Box Mod"
credits="Pokemon TCG Community"
authors="ETB Mod Team"
description='''Brings Pokemon TCG Elite Trainer Boxes to Minecraft!

Features in v2.3:
- 13 unique ETB designs from real Pokemon TCG sets
- Custom 3D models with accurate proportions  
- Directional placement - rotate your ETBs
- Scissors tool to open ETBs and get booster packs
- 12 unique booster pack items with high-quality textures
- Gamer Table - Interactive block with GUI
- NEW: Open booster packs on the Gamer Table!
- NEW: Realistic card pack opening experience
- NEW: 10 cards per pack with accurate rarity distribution
- NEW: Navigate through cards with arrow keys
- NEW: Fully self-contained - all card data included in mod!
- NEW: 10 complete Pokemon TCG sets with 700+ cards
- NEW: Cards load from mod resources (works on any server)
- Optimized card images for small mod size (~20MB total)
'''

[[dependencies.etbmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.etbmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
