package com.example.etbmod.registry;

import com.example.etbmod.ETBMod;
import com.example.etbmod.blocks.ETBBlock;
import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;

/**
 * Auto-generated ETB registry
 * Generated by generate_assets_and_registry.py
 */
public class GeneratedETBRegistry {
    
    public static void registerETBs() {
        ModBlocks.registerETB("etb_151");
        ModBlocks.registerETB("etb_black_bolt");
        ModBlocks.registerETB("etb_brilliant_stars");
        ModBlocks.registerETB("etb_celebrations");
        ModBlocks.registerETB("etb_destined_rivals");
        ModBlocks.registerETB("etb_generations");
        ModBlocks.registerETB("etb_groudon");
        ModBlocks.registerETB("etb_journey_together");
        ModBlocks.registerETB("etb_kyogre");
        ModBlocks.registerETB("etb_prismatic_evolutions");
        ModBlocks.registerETB("etb_surging_sparks");
        ModBlocks.registerETB("etb_white_flare");
    }
    
    public static void registerETBItems() {
        // Items are automatically registered via ModItems static block
    }
}
